CC = g++
CFLAGS = -std=c++11 -Wall
EXEC_NAME = hillclimber
INCLUDES = eval.o #eval1.o
OBJ_FILES = main.cpp

$(EXEC_NAME) : $(OBJ_FILES)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $(OBJ_FILES)

# .cpp.0:
# 	$(CC) $(CFLAGS) -c $<

